-- Add PACMAN reaction. Replace CHECK constraint with new allowed set.
ALTER TABLE HRMS.HR_BULLETIN_REACTION DROP CONSTRAINT CHK_BRXN_TYPE;

ALTER TABLE HRMS.HR_BULLETIN_REACTION
    ADD CONSTRAINT CHK_BRXN_TYPE
        CHECK (REACTION IN ('LIKE','LOVE','HAHA','WOW','SAD','ANGRY','PACMAN'));

COMMIT;
